<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-16T14:43:14 IST" name="Suite" finished-at="2025-06-16T14:43:24 IST" duration-ms="10410">
    <groups>
    </groups>
    <test started-at="2025-06-16T14:43:14 IST" name="Test" finished-at="2025-06-16T14:43:24 IST" duration-ms="10410">
      <class name="ListenerTutorial.TestCaseClass">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ListenerTutorial.TestCaseClass@62ddbd7e]" started-at="2025-06-16T14:43:14 IST" name="setUp" finished-at="2025-06-16T14:43:21 IST" duration-ms="6991" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogo()[pri:0, instance:ListenerTutorial.TestCaseClass@62ddbd7e]" started-at="2025-06-16T14:43:21 IST" name="testLogo" finished-at="2025-06-16T14:43:24 IST" duration-ms="3055" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogo -->
        <test-method signature="testAppUrl()[pri:1, instance:ListenerTutorial.TestCaseClass@62ddbd7e]" started-at="2025-06-16T14:43:24 IST" name="testAppUrl" finished-at="2025-06-16T14:43:24 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at ListenerTutorial.TestCaseClass.testAppUrl(TestCaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppUrl -->
        <test-method signature="testHomePageTitle()[pri:2, instance:ListenerTutorial.TestCaseClass@62ddbd7e]" started-at="2025-06-16T14:43:24 IST" name="testHomePageTitle" finished-at="2025-06-16T14:43:24 IST" depends-on-methods="ListenerTutorial.TestCaseClass.testAppUrl" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ListenerTutorial.TestCaseClass.testHomePageTitle() on instance ListenerTutorial.TestCaseClass@62ddbd7e depends on not successfully finished methods 
[ListenerTutorial.TestCaseClass.testAppUrl() on instance ListenerTutorial.TestCaseClass@62ddbd7e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ListenerTutorial.TestCaseClass.testHomePageTitle() on instance ListenerTutorial.TestCaseClass@62ddbd7e depends on not successfully finished methods 
[ListenerTutorial.TestCaseClass.testAppUrl() on instance ListenerTutorial.TestCaseClass@62ddbd7e]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePageTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ListenerTutorial.TestCaseClass@62ddbd7e]" started-at="2025-06-16T14:43:24 IST" name="tearDown" finished-at="2025-06-16T14:43:24 IST" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ListenerTutorial.TestCaseClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
